
package com.smartCity.gateway.entities.citizen;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "CitizenService", targetNamespace = "http://services.finesService.smartCity.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CitizenService {


    /**
     * 
     * @param id
     * @return
     *     returns com.smartCity.gateway.entities.citizen.Citizen
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCitizenFines", targetNamespace = "http://services.finesService.smartCity.com/", className = "com.smartCity.gateway.entities.citizen.GetCitizenFines")
    @ResponseWrapper(localName = "getCitizenFinesResponse", targetNamespace = "http://services.finesService.smartCity.com/", className = "com.smartCity.gateway.entities.citizen.GetCitizenFinesResponse")
    @Action(input = "http://services.finesService.smartCity.com/CitizenService/getCitizenFinesRequest", output = "http://services.finesService.smartCity.com/CitizenService/getCitizenFinesResponse")
    public Citizen getCitizenFines(
        @WebParam(name = "id", targetNamespace = "")
        Long id);

    /**
     * 
     * @return
     *     returns java.util.List<com.smartCity.gateway.entities.citizen.Citizen>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCitizens", targetNamespace = "http://services.finesService.smartCity.com/", className = "com.smartCity.gateway.entities.citizen.GetCitizens")
    @ResponseWrapper(localName = "getCitizensResponse", targetNamespace = "http://services.finesService.smartCity.com/", className = "com.smartCity.gateway.entities.citizen.GetCitizensResponse")
    @Action(input = "http://services.finesService.smartCity.com/CitizenService/getCitizensRequest", output = "http://services.finesService.smartCity.com/CitizenService/getCitizensResponse")
    public List<Citizen> getCitizens();

    /**
     * 
     * @param citizen
     * @return
     *     returns com.smartCity.gateway.entities.citizen.Citizen
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addCitizen", targetNamespace = "http://services.finesService.smartCity.com/", className = "com.smartCity.gateway.entities.citizen.AddCitizen")
    @ResponseWrapper(localName = "addCitizenResponse", targetNamespace = "http://services.finesService.smartCity.com/", className = "com.smartCity.gateway.entities.citizen.AddCitizenResponse")
    @Action(input = "http://services.finesService.smartCity.com/CitizenService/addCitizenRequest", output = "http://services.finesService.smartCity.com/CitizenService/addCitizenResponse")
    public Citizen addCitizen(
        @WebParam(name = "citizen", targetNamespace = "")
        Citizen citizen);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.smartCity.gateway.entities.citizen.Citizen
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCitizenById", targetNamespace = "http://services.finesService.smartCity.com/", className = "com.smartCity.gateway.entities.citizen.GetCitizenById")
    @ResponseWrapper(localName = "getCitizenByIdResponse", targetNamespace = "http://services.finesService.smartCity.com/", className = "com.smartCity.gateway.entities.citizen.GetCitizenByIdResponse")
    @Action(input = "http://services.finesService.smartCity.com/CitizenService/getCitizenByIdRequest", output = "http://services.finesService.smartCity.com/CitizenService/getCitizenByIdResponse")
    public Citizen getCitizenById(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

}
