
package com.smartCity.gateway.entities.fines;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "FinesService", targetNamespace = "http://services.finesService.smartCity.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FinesService {


    /**
     * 
     * @param idCitizen
     * @param idFine
     * @return
     *     returns com.smartCity.gateway.entities.fines.Fine
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFineByIdFineAndIdCitizen", targetNamespace = "http://services.finesService.smartCity.com/", className = "com.smartCity.gateway.entities.fines.GetFineByIdFineAndIdCitizen")
    @ResponseWrapper(localName = "getFineByIdFineAndIdCitizenResponse", targetNamespace = "http://services.finesService.smartCity.com/", className = "com.smartCity.gateway.entities.fines.GetFineByIdFineAndIdCitizenResponse")
    @Action(input = "http://services.finesService.smartCity.com/FinesService/getFineByIdFineAndIdCitizenRequest", output = "http://services.finesService.smartCity.com/FinesService/getFineByIdFineAndIdCitizenResponse")
    public Fine getFineByIdFineAndIdCitizen(
        @WebParam(name = "idFine", targetNamespace = "")
        Long idFine,
        @WebParam(name = "idCitizen", targetNamespace = "")
        Long idCitizen);

    /**
     * 
     * @return
     *     returns java.util.List<com.smartCity.gateway.entities.fines.Fine>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFines", targetNamespace = "http://services.finesService.smartCity.com/", className = "com.smartCity.gateway.entities.fines.GetFines")
    @ResponseWrapper(localName = "getFinesResponse", targetNamespace = "http://services.finesService.smartCity.com/", className = "com.smartCity.gateway.entities.fines.GetFinesResponse")
    @Action(input = "http://services.finesService.smartCity.com/FinesService/getFinesRequest", output = "http://services.finesService.smartCity.com/FinesService/getFinesResponse")
    public List<Fine> getFines();

    /**
     * 
     * @param id
     * @return
     *     returns com.smartCity.gateway.entities.fines.Fine
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFine", targetNamespace = "http://services.finesService.smartCity.com/", className = "com.smartCity.gateway.entities.fines.GetFine")
    @ResponseWrapper(localName = "getFineResponse", targetNamespace = "http://services.finesService.smartCity.com/", className = "com.smartCity.gateway.entities.fines.GetFineResponse")
    @Action(input = "http://services.finesService.smartCity.com/FinesService/getFineRequest", output = "http://services.finesService.smartCity.com/FinesService/getFineResponse")
    public Fine getFine(
        @WebParam(name = "id", targetNamespace = "")
        Long id);

    /**
     * 
     * @param fine
     * @return
     *     returns com.smartCity.gateway.entities.fines.Fine
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addFine", targetNamespace = "http://services.finesService.smartCity.com/", className = "com.smartCity.gateway.entities.fines.AddFine")
    @ResponseWrapper(localName = "addFineResponse", targetNamespace = "http://services.finesService.smartCity.com/", className = "com.smartCity.gateway.entities.fines.AddFineResponse")
    @Action(input = "http://services.finesService.smartCity.com/FinesService/addFineRequest", output = "http://services.finesService.smartCity.com/FinesService/addFineResponse")
    public Fine addFine(
        @WebParam(name = "fine", targetNamespace = "")
        Fine fine);

}
